# Generated by Django 5.1.3 on 2025-12-18 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_studysession_date_studysession_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
