# Generated by Django 5.1.3 on 2026-01-13 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studysession_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 19, 54, 9, 75592)),
        ),
    ]