# Generated by Django 5.1.3 on 2026-01-13 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studysession_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='studysession',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 19, 47, 2, 527164)),
        ),
    ]
